// Textes de l'interface en anglais.
// L'anglais sert aussi de secours : un texte absent d'une autre langue s'affiche en anglais.

import pays from 'i18n-iso-countries/langs/en.json'; // noms des pays en anglais

export default {
  code: 'en',
  nom: 'English',
  pays,
  textes: {
    monde: 'World',
    europe: 'Europe',
    afrique: 'Africa',
    asie: 'Asia',
    ameriques: 'Americas',
    oceanie: 'Oceania',
    titreCarte: 'GRN map · 6,700+ languages',
    retourCarte: '↩ Back to the map',
    aucuneLangue: 'No language recorded for this country.',
    diaspora: 'diaspora',
    // Panneau d'un pays ({n} est remplacé par le nombre)
    choisissezLangue: 'Choose your heart language',
    languesNatives: '{n} native languages',
    uneLangueNative: '1 native language',
    afficherDiaspora: 'Also show diaspora languages',
    fermerPanneau: 'Close the panel',
    // Fenêtre du QR code
    scannez: 'Scan with your phone to listen',
    ouvrirIci: 'Open here',
    // Écran 5fish ({temps} est remplacé par m:ss, {n} par des secondes)
    retourDans: 'Back to the map in {temps}',
    toujoursLaQuestion: 'Are you still there?',
    retourDansSecondes: 'Back to the map in {n} s',
    toujoursLa: 'I’m still here',
    recherche: 'Search',
    rechercheIndication: 'Search for a language or a country…',
    aucunResultat: 'No results.',
    resultatPays: 'Country',
    resultatLangue: 'Language',
    veilleDansSecondes: 'Back to the home screen in {n} s',
    reglages: 'Settings',
    // Écran des réglages
    reglagesTitre: 'Kiosk settings',
    reglagesSousTitre: 'These settings are saved on this device.',
    codeAcces: 'Access code',
    valider: 'Confirm',
    codeIncorrect: 'Incorrect code.',
    langueInterface: 'Kiosk language',
    dureeImage: 'Duration of each slideshow image (seconds)',
    inactivite: 'Back to the slideshow after inactivity (seconds)',
    retour5fish: 'Back to the map from the GRN website (seconds)',
    retour5fishAide: '0 = no automatic return.',
    imagesDiaporama: 'Slideshow images',
    diaporamaOrigine: 'Original slideshow, {n} images.',
    diaporamaPdf: 'PDF “{nom}”, {n} images, loaded on {date}.',
    pdfAide: 'One PDF page = one image. Landscape 16:9 recommended.',
    chargerPdf: 'Load a PDF',
    boutonDiaporamaOrigine: 'Original slideshow',
    pdfEnCours: 'Reading the PDF…',
    pdfErreur: 'This PDF could not be read.',
    bandeauTitre: 'Church welcome banner',
    bandeauAfficher: 'Show the banner',
    bandeauLogo: 'Church logo (PNG, JPG or SVG)',
    aucunLogo: 'No logo',
    chargerLogo: 'Load a logo',
    retirerLogo: 'Remove the logo',
    logoErreur: 'This image could not be read.',
    bandeauPhrase: 'Welcome message ({langue})',
    bandeauPhraseAide: 'An empty box shows the English message (or the first one filled in).',
    nouveauCode: 'New church access code',
    nouveauCodeAide: 'Leave empty to keep the current code.',
    enregistrer: 'Save',
    copierLien: 'Copy configuration link',
    lienCopie: 'Configuration link copied.',
    lienACopier: 'Copy this link:',
    valeursDefaut: 'Default values',
    defautsRemis: 'Default values restored. Tap “Save” to keep them.',
    donnees5fish: '5fish data: updated on {date}',
    donneesExemple: '(sample data)',
    pleinEcran: 'Full screen',
    sortiePleinEcran: 'Exit full screen',
    zoomPlus: 'Zoom in',
    zoomMoins: 'Zoom out',
    fermer: 'Close',
    logoAria: 'Global Recordings Network — grneu.org',
  },
};
