// Textes de l'interface en espagnol.
// Traduction préparée par Claude — À FAIRE RELIRE par une personne de langue maternelle espagnole.

import pays from 'i18n-iso-countries/langs/es.json'; // noms des pays en espagnol

export default {
  code: 'es',
  nom: 'Español',
  pays,
  textes: {
    monde: 'Mundo',
    europe: 'Europa',
    afrique: 'África',
    asie: 'Asia',
    ameriques: 'Américas',
    oceanie: 'Oceanía',
    titreCarte: 'GRN map · más de 6.700 idiomas',
    retourCarte: '↩ Volver al mapa',
    aucuneLangue: 'No hay ningún idioma registrado para este país.',
    diaspora: 'diáspora',
    // Panneau d'un pays ({n} est remplacé par le nombre)
    choisissezLangue: 'Elija la lengua de su corazón',
    languesNatives: '{n} idiomas nativos',
    uneLangueNative: '1 idioma nativo',
    afficherDiaspora: 'Mostrar también los idiomas de la diáspora',
    fermerPanneau: 'Cerrar el panel',
    // Fenêtre du QR code
    scannez: 'Escanee con su teléfono para escuchar',
    ouvrirIci: 'Abrir aquí',
    // Écran 5fish ({temps} est remplacé par m:ss, {n} par des secondes)
    retourDans: 'Volver al mapa en {temps}',
    toujoursLaQuestion: '¿Sigue ahí?',
    retourDansSecondes: 'Volver al mapa en {n} s',
    toujoursLa: 'Sigo aquí',
    recherche: 'Buscar',
    rechercheIndication: 'Buscar un idioma o un país…',
    aucunResultat: 'Sin resultados.',
    resultatPays: 'País',
    resultatLangue: 'Idioma',
    veilleDansSecondes: 'Volver a la pantalla de inicio en {n} s',
    reglages: 'Ajustes',
    // Écran des réglages
    reglagesTitre: 'Ajustes del terminal',
    reglagesSousTitre: 'Estos ajustes se guardan en este dispositivo.',
    codeAcces: 'Código de acceso',
    valider: 'Confirmar',
    codeIncorrect: 'Código incorrecto.',
    langueInterface: 'Idioma del terminal',
    dureeImage: 'Duración de cada imagen de la presentación (segundos)',
    inactivite: 'Volver a la presentación tras inactividad (segundos)',
    retour5fish: 'Volver al mapa desde el sitio de GRN (segundos)',
    retour5fishAide: '0 = sin regreso automático. Solo en modo terminal.',
    imagesDiaporama: 'Imágenes de la presentación',
    diaporamaOrigine: 'Presentación original, {n} imágenes.',
    diaporamaPdf: 'PDF «{nom}», {n} imágenes, cargado el {date}.',
    pdfAide: 'Una página del PDF = una imagen. Se recomienda formato horizontal 16:9.',
    chargerPdf: 'Cargar un PDF',
    boutonDiaporamaOrigine: 'Presentación original',
    pdfEnCours: 'Leyendo el PDF…',
    pdfErreur: 'No se pudo leer este PDF.',
    bandeauTitre: 'Banner de bienvenida de la iglesia',
    bandeauAfficher: 'Mostrar el banner',
    bandeauLogo: 'Logotipo de la iglesia (PNG, JPG o SVG)',
    aucunLogo: 'Sin logotipo',
    chargerLogo: 'Cargar un logotipo',
    retirerLogo: 'Quitar el logotipo',
    logoErreur: 'No se pudo leer esta imagen.',
    bandeauPhrase: 'Mensaje de bienvenida ({langue})',
    bandeauPhraseAide: 'Una casilla vacía muestra el mensaje en inglés (o el primero que esté completado).',
    nouveauCode: 'Nuevo código de acceso de la iglesia',
    nouveauCodeAide: 'Déjelo vacío para conservar el código actual.',
    enregistrer: 'Guardar',
    copierLien: 'Copiar el enlace de configuración',
    lienCopie: 'Enlace de configuración copiado.',
    lienACopier: 'Copie este enlace:',
    valeursDefaut: 'Valores predeterminados',
    defautsRemis: 'Valores predeterminados restablecidos. Toque «Guardar» para conservarlos.',
    donnees5fish: 'Datos de 5fish: actualizados el {date}',
    donneesExemple: '(datos de ejemplo)',
    pleinEcran: 'Pantalla completa',
    zoomPlus: 'Acercar',
    zoomMoins: 'Alejar',
    fermer: 'Cerrar',
    logoAria: 'Global Recordings Network — grneu.org',
  },
};
