// Textes de l'interface en français.
// Chaque langue a son propre fichier dans ce dossier, avec les mêmes clés.

import pays from 'i18n-iso-countries/langs/fr.json'; // noms des pays en français

export default {
  code: 'fr',
  nom: 'Français',      // nom affiché dans la liste des réglages (écrit dans la langue elle-même)
  pays,
  textes: {
    monde: 'Monde',
    europe: 'Europe',
    afrique: 'Afrique',
    asie: 'Asie',
    ameriques: 'Amériques',
    oceanie: 'Océanie',
    titreCarte: 'GRN map · + de 6 700 langues',
    retourCarte: '↩ Retour à la carte',
    aucuneLangue: 'Aucune langue enregistrée pour ce pays.',
    diaspora: 'diaspora',
    // Panneau d'un pays ({n} est remplacé par le nombre)
    choisissezLangue: 'Choisissez la langue de votre cœur',
    languesNatives: '{n} langues natives',
    uneLangueNative: '1 langue native',
    afficherDiaspora: 'Afficher aussi les langues diaspora',
    fermerPanneau: 'Fermer le panneau',
    // Fenêtre du QR code
    scannez: 'Scannez avec votre téléphone pour écouter',
    ouvrirIci: 'Ouvrir ici',
    // Écran 5fish ({temps} est remplacé par m:ss, {n} par des secondes)
    retourDans: 'Retour à la carte dans {temps}',
    toujoursLaQuestion: 'Êtes-vous toujours là ?',
    retourDansSecondes: 'Retour à la carte dans {n} s',
    toujoursLa: 'Je suis toujours là',
    recherche: 'Rechercher',
    rechercheIndication: 'Rechercher une langue ou un pays…',
    aucunResultat: 'Aucun résultat.',
    resultatPays: 'Pays',
    resultatLangue: 'Langue',
    veilleDansSecondes: 'Retour à l’accueil dans {n} s',
    reglages: 'Réglages',
    // Écran des réglages
    reglagesTitre: 'Réglages de la borne',
    reglagesSousTitre: 'Ces réglages sont enregistrés sur cet appareil.',
    codeAcces: 'Code d’accès',
    valider: 'Valider',
    codeIncorrect: 'Code incorrect.',
    langueInterface: 'Langue de la borne',
    dureeImage: 'Durée de chaque image du diaporama (secondes)',
    inactivite: 'Retour au diaporama après inactivité (secondes)',
    retour5fish: 'Retour à la carte depuis le site GRN (secondes)',
    retour5fishAide: '0 = pas de retour automatique.',
    imagesDiaporama: 'Images du diaporama',
    diaporamaOrigine: 'Diaporama d’origine, {n} images.',
    diaporamaPdf: 'PDF « {nom} », {n} images, chargé le {date}.',
    pdfAide: 'Une page du PDF = une image. Format paysage 16/9 conseillé.',
    chargerPdf: 'Charger un PDF',
    boutonDiaporamaOrigine: 'Diaporama d’origine',
    pdfEnCours: 'Lecture du PDF en cours…',
    pdfErreur: 'Ce PDF n’a pas pu être lu.',
    bandeauTitre: 'Bandeau d’accueil de l’église',
    bandeauAfficher: 'Afficher le bandeau',
    bandeauLogo: 'Logo de l’église (PNG, JPG ou SVG)',
    aucunLogo: 'Aucun logo',
    chargerLogo: 'Charger un logo',
    retirerLogo: 'Retirer le logo',
    logoErreur: 'Cette image n’a pas pu être lue.',
    bandeauPhrase: 'Phrase d’accueil ({langue})',
    bandeauPhraseAide: 'Une case vide affiche la phrase en anglais (ou la première phrase remplie).',
    nouveauCode: 'Nouveau code d’accès de l’église',
    nouveauCodeAide: 'Laisser vide pour garder le code actuel.',
    enregistrer: 'Enregistrer',
    copierLien: 'Copier le lien de configuration',
    lienCopie: 'Lien de configuration copié.',
    lienACopier: 'Copiez ce lien :',
    valeursDefaut: 'Valeurs par défaut',
    defautsRemis: 'Valeurs par défaut remises. Touchez « Enregistrer » pour les garder.',
    donnees5fish: 'Données 5fish : mise à jour du {date}',
    donneesExemple: '(données d’exemple)',
    pleinEcran: 'Plein écran',
    sortiePleinEcran: 'Quitter le plein écran',
    zoomPlus: 'Zoomer',
    zoomMoins: 'Dézoomer',
    fermer: 'Fermer',
    logoAria: 'Global Recordings Network — grneu.org',
  },
};
