// Textes de l'interface en italien.
// Traduction préparée par Claude — À FAIRE RELIRE par une personne de langue maternelle italienne.

import pays from 'i18n-iso-countries/langs/it.json'; // noms des pays en italien

export default {
  code: 'it',
  nom: 'Italiano',
  pays,
  textes: {
    monde: 'Mondo',
    europe: 'Europa',
    afrique: 'Africa',
    asie: 'Asia',
    ameriques: 'Americhe',
    oceanie: 'Oceania',
    titreCarte: 'GRN map · oltre 6.700 lingue',
    retourCarte: '↩ Torna alla mappa',
    aucuneLangue: 'Nessuna lingua registrata per questo paese.',
    diaspora: 'diaspora',
    // Panneau d'un pays ({n} est remplacé par le nombre)
    choisissezLangue: 'Scegli la lingua del tuo cuore',
    languesNatives: '{n} lingue native',
    uneLangueNative: '1 lingua nativa',
    afficherDiaspora: 'Mostra anche le lingue della diaspora',
    fermerPanneau: 'Chiudi il pannello',
    // Fenêtre du QR code
    scannez: 'Scansiona con il telefono per ascoltare',
    ouvrirIci: 'Apri qui',
    // Écran 5fish ({temps} est remplacé par m:ss, {n} par des secondes)
    retourDans: 'Ritorno alla mappa tra {temps}',
    toujoursLaQuestion: 'Sei ancora qui?',
    retourDansSecondes: 'Ritorno alla mappa tra {n} s',
    toujoursLa: 'Sono ancora qui',
    recherche: 'Cerca',
    rechercheIndication: 'Cerca una lingua o un paese…',
    aucunResultat: 'Nessun risultato.',
    resultatPays: 'Paese',
    resultatLangue: 'Lingua',
    veilleDansSecondes: 'Ritorno alla schermata iniziale tra {n} s',
    reglages: 'Impostazioni',
    // Écran des réglages
    reglagesTitre: 'Impostazioni del totem',
    reglagesSousTitre: 'Queste impostazioni sono salvate su questo dispositivo.',
    codeAcces: 'Codice di accesso',
    valider: 'Conferma',
    codeIncorrect: 'Codice errato.',
    langueInterface: 'Lingua del totem',
    dureeImage: 'Durata di ogni immagine della presentazione (secondi)',
    inactivite: 'Ritorno alla presentazione dopo inattività (secondi)',
    retour5fish: 'Ritorno alla mappa dal sito GRN (secondi)',
    retour5fishAide: '0 = nessun ritorno automatico. Attivo solo in modalità totem.',
    imagesDiaporama: 'Immagini della presentazione',
    diaporamaOrigine: 'Presentazione originale, {n} immagini.',
    diaporamaPdf: 'PDF «{nom}», {n} immagini, caricato il {date}.',
    pdfAide: 'Una pagina del PDF = un’immagine. Consigliato il formato orizzontale 16:9.',
    chargerPdf: 'Carica un PDF',
    boutonDiaporamaOrigine: 'Presentazione originale',
    pdfEnCours: 'Lettura del PDF in corso…',
    pdfErreur: 'Impossibile leggere questo PDF.',
    bandeauTitre: 'Banner di benvenuto della chiesa',
    bandeauAfficher: 'Mostra il banner',
    bandeauLogo: 'Logo della chiesa (PNG, JPG o SVG)',
    aucunLogo: 'Nessun logo',
    chargerLogo: 'Carica un logo',
    retirerLogo: 'Rimuovi il logo',
    logoErreur: 'Impossibile leggere questa immagine.',
    bandeauPhrase: 'Messaggio di benvenuto ({langue})',
    bandeauPhraseAide: 'Una casella vuota mostra il messaggio in inglese (o il primo compilato).',
    nouveauCode: 'Nuovo codice di accesso della chiesa',
    nouveauCodeAide: 'Lascia vuoto per mantenere il codice attuale.',
    enregistrer: 'Salva',
    copierLien: 'Copia il link di configurazione',
    lienCopie: 'Link di configurazione copiato.',
    lienACopier: 'Copia questo link:',
    valeursDefaut: 'Valori predefiniti',
    defautsRemis: 'Valori predefiniti ripristinati. Tocca «Salva» per mantenerli.',
    donnees5fish: 'Dati 5fish: aggiornati il {date}',
    donneesExemple: '(dati di esempio)',
    pleinEcran: 'Schermo intero',
    zoomPlus: 'Ingrandisci',
    zoomMoins: 'Riduci',
    fermer: 'Chiudi',
    logoAria: 'Global Recordings Network — grneu.org',
  },
};
