// Textes de l'interface en néerlandais.
// Traduction préparée par Claude — À FAIRE RELIRE par une personne de langue maternelle néerlandaise.

import pays from 'i18n-iso-countries/langs/nl.json'; // noms des pays en néerlandais

export default {
  code: 'nl',
  nom: 'Nederlands',
  pays,
  textes: {
    monde: 'Wereld',
    europe: 'Europa',
    afrique: 'Afrika',
    asie: 'Azië',
    ameriques: 'Amerika',
    oceanie: 'Oceanië',
    titreCarte: 'GRN map · meer dan 6.700 talen',
    retourCarte: '↩ Terug naar de kaart',
    aucuneLangue: 'Voor dit land is geen taal geregistreerd.',
    diaspora: 'diaspora',
    // Panneau d'un pays ({n} est remplacé par le nombre)
    choisissezLangue: 'Kies uw hartstaal',
    languesNatives: '{n} inheemse talen',
    uneLangueNative: '1 inheemse taal',
    afficherDiaspora: 'Ook talen van de diaspora tonen',
    fermerPanneau: 'Paneel sluiten',
    // Fenêtre du QR code
    scannez: 'Scan met uw telefoon om te luisteren',
    ouvrirIci: 'Hier openen',
    // Écran 5fish ({temps} est remplacé par m:ss, {n} par des secondes)
    retourDans: 'Terug naar de kaart over {temps}',
    toujoursLaQuestion: 'Bent u er nog?',
    retourDansSecondes: 'Terug naar de kaart over {n} s',
    toujoursLa: 'Ik ben er nog',
    recherche: 'Zoeken',
    rechercheIndication: 'Zoek een taal of een land…',
    aucunResultat: 'Geen resultaten.',
    resultatPays: 'Land',
    resultatLangue: 'Taal',
    veilleDansSecondes: 'Terug naar het startscherm over {n} s',
    reglages: 'Instellingen',
    // Écran des réglages
    reglagesTitre: 'Instellingen van de zuil',
    reglagesSousTitre: 'Deze instellingen worden op dit apparaat opgeslagen.',
    codeAcces: 'Toegangscode',
    valider: 'Bevestigen',
    codeIncorrect: 'Onjuiste code.',
    langueInterface: 'Taal van de zuil',
    dureeImage: 'Duur van elke afbeelding van de diavoorstelling (seconden)',
    inactivite: 'Terug naar de diavoorstelling na inactiviteit (seconden)',
    retour5fish: 'Terug naar de kaart vanaf de GRN-website (seconden)',
    retour5fishAide: '0 = niet automatisch terug.',
    imagesDiaporama: 'Afbeeldingen van de diavoorstelling',
    diaporamaOrigine: 'Oorspronkelijke diavoorstelling, {n} afbeeldingen.',
    diaporamaPdf: 'PDF ‘{nom}’, {n} afbeeldingen, geladen op {date}.',
    pdfAide: 'Eén pagina van de PDF = één afbeelding. Liggend formaat 16:9 aanbevolen.',
    chargerPdf: 'Een PDF laden',
    boutonDiaporamaOrigine: 'Oorspronkelijke diavoorstelling',
    pdfEnCours: 'PDF wordt gelezen…',
    pdfErreur: 'Deze PDF kon niet worden gelezen.',
    bandeauTitre: 'Welkomstbanner van de kerk',
    bandeauAfficher: 'Banner tonen',
    bandeauLogo: 'Logo van de kerk (PNG, JPG of SVG)',
    aucunLogo: 'Geen logo',
    chargerLogo: 'Een logo laden',
    retirerLogo: 'Logo verwijderen',
    logoErreur: 'Deze afbeelding kon niet worden gelezen.',
    bandeauPhrase: 'Welkomstbericht ({langue})',
    bandeauPhraseAide: 'Een leeg vak toont het Engelse bericht (of het eerste ingevulde).',
    nouveauCode: 'Nieuwe toegangscode van de kerk',
    nouveauCodeAide: 'Leeg laten om de huidige code te behouden.',
    enregistrer: 'Opslaan',
    copierLien: 'Configuratielink kopiëren',
    lienCopie: 'Configuratielink gekopieerd.',
    lienACopier: 'Kopieer deze link:',
    valeursDefaut: 'Standaardwaarden',
    defautsRemis: 'Standaardwaarden hersteld. Tik op ‘Opslaan’ om ze te behouden.',
    donnees5fish: '5fish-gegevens: bijgewerkt op {date}',
    donneesExemple: '(voorbeeldgegevens)',
    pleinEcran: 'Volledig scherm',
    sortiePleinEcran: 'Volledig scherm verlaten',
    zoomPlus: 'Inzoomen',
    zoomMoins: 'Uitzoomen',
    fermer: 'Sluiten',
    logoAria: 'Global Recordings Network — grneu.org',
  },
};
