// Textes de l'interface en portugais (portugais d'Europe).
// Traduction préparée par Claude — À FAIRE RELIRE par une personne de langue maternelle portugaise.

import pays from 'i18n-iso-countries/langs/pt.json'; // noms des pays en portugais

export default {
  code: 'pt',
  nom: 'Português',
  pays,
  textes: {
    monde: 'Mundo',
    europe: 'Europa',
    afrique: 'África',
    asie: 'Ásia',
    ameriques: 'Américas',
    oceanie: 'Oceânia',
    titreCarte: 'GRN map · mais de 6700 línguas',
    retourCarte: '↩ Voltar ao mapa',
    aucuneLangue: 'Nenhuma língua registada para este país.',
    diaspora: 'diáspora',
    // Panneau d'un pays ({n} est remplacé par le nombre)
    choisissezLangue: 'Escolha a língua do seu coração',
    languesNatives: '{n} línguas nativas',
    uneLangueNative: '1 língua nativa',
    afficherDiaspora: 'Mostrar também as línguas da diáspora',
    fermerPanneau: 'Fechar o painel',
    // Fenêtre du QR code
    scannez: 'Digitalize com o seu telemóvel para ouvir',
    ouvrirIci: 'Abrir aqui',
    // Écran 5fish ({temps} est remplacé par m:ss, {n} par des secondes)
    retourDans: 'Voltar ao mapa dentro de {temps}',
    toujoursLaQuestion: 'Ainda está aí?',
    retourDansSecondes: 'Voltar ao mapa dentro de {n} s',
    toujoursLa: 'Ainda estou aqui',
    recherche: 'Pesquisar',
    rechercheIndication: 'Pesquisar uma língua ou um país…',
    aucunResultat: 'Sem resultados.',
    resultatPays: 'País',
    resultatLangue: 'Língua',
    veilleDansSecondes: 'Voltar ao ecrã inicial dentro de {n} s',
    reglages: 'Definições',
    // Écran des réglages
    reglagesTitre: 'Definições do terminal',
    reglagesSousTitre: 'Estas definições são guardadas neste dispositivo.',
    codeAcces: 'Código de acesso',
    valider: 'Confirmar',
    codeIncorrect: 'Código incorreto.',
    langueInterface: 'Língua do terminal',
    dureeImage: 'Duração de cada imagem da apresentação (segundos)',
    inactivite: 'Voltar à apresentação após inatividade (segundos)',
    retour5fish: 'Voltar ao mapa a partir do site da GRN (segundos)',
    retour5fishAide: '0 = sem regresso automático.',
    imagesDiaporama: 'Imagens da apresentação',
    diaporamaOrigine: 'Apresentação original, {n} imagens.',
    diaporamaPdf: 'PDF «{nom}», {n} imagens, carregado em {date}.',
    pdfAide: 'Uma página do PDF = uma imagem. Recomenda-se o formato horizontal 16:9.',
    chargerPdf: 'Carregar um PDF',
    boutonDiaporamaOrigine: 'Apresentação original',
    pdfEnCours: 'A ler o PDF…',
    pdfErreur: 'Não foi possível ler este PDF.',
    bandeauTitre: 'Faixa de boas-vindas da igreja',
    bandeauAfficher: 'Mostrar a faixa',
    bandeauLogo: 'Logótipo da igreja (PNG, JPG ou SVG)',
    aucunLogo: 'Sem logótipo',
    chargerLogo: 'Carregar um logótipo',
    retirerLogo: 'Remover o logótipo',
    logoErreur: 'Não foi possível ler esta imagem.',
    bandeauPhrase: 'Mensagem de boas-vindas ({langue})',
    bandeauPhraseAide: 'Uma caixa vazia mostra a mensagem em inglês (ou a primeira preenchida).',
    nouveauCode: 'Novo código de acesso da igreja',
    nouveauCodeAide: 'Deixe vazio para manter o código atual.',
    enregistrer: 'Guardar',
    copierLien: 'Copiar a ligação de configuração',
    lienCopie: 'Ligação de configuração copiada.',
    lienACopier: 'Copie esta ligação:',
    valeursDefaut: 'Valores predefinidos',
    defautsRemis: 'Valores predefinidos repostos. Toque em «Guardar» para os manter.',
    donnees5fish: 'Dados 5fish: atualizados em {date}',
    donneesExemple: '(dados de exemplo)',
    pleinEcran: 'Ecrã inteiro',
    zoomPlus: 'Aumentar',
    zoomMoins: 'Diminuir',
    fermer: 'Fechar',
    logoAria: 'Global Recordings Network — grneu.org',
  },
};
